[profile.default]
  libs = ["lib"]
  out = "out"
  src = "src"
  test = "test"
  solc = "0.8.26"



  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

  ast = true
  build_info = true
  extra_output = ["storageLayout"]
  ffi = true

[rpc_endpoints]
  sepolia-unichain = "https://sepolia.unichain.org/"
  sepolia-base = "https://sepolia.base.org/"
